name: Send Discord Notification

# This workflow can be triggered manually
on:
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Optional custom message to include'
        required: false
        default: ''

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Discord Notification
        run: |
          # Get current date and time
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S UTC')
          
          # Create the message
          MESSAGE="🕐 Current Date & Time: $CURRENT_TIME"
          
          # Add custom message if provided
          if [ ! -z "${{ github.event.inputs.custom_message }}" ]; then
            MESSAGE="$MESSAGE\n💬 ${{ github.event.inputs.custom_message }}"
          fi
          
          # Send to Discord webhook
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"$MESSAGE\"}" \
               "${{ secrets.WEBHOOK_URL }}"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
