name: Dummy Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo dummy message
        run: echo "This is a dummy workflow running every 5 minutes."
