name: Simulate and Send Discord Notification

on:
  workflow_dispatch:
    inputs:
      simulation_command:
        description: 'python -u src/main.py --canon --output --headless --rng-mode'
        required: false
        default: 'python -u src/main.py --rng-mode date --canon --output --headless'

jobs:
  simulate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run simulation
        env:
          SDL_AUDIODRIVER: dummy
          WINNER_REPORT_WEBHOOK_URL: ${{ secrets.WINNER_REPORT_WEBHOOK_URL }}
        run: |
          python -u send_race_start.py
          ${{ github.event.inputs.simulation_command }}

      - name: Send Discord notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WINNER_REPORT_WEBHOOK_URL: ${{ secrets.WINNER_REPORT_WEBHOOK_URL }}
        run: |
          python -u send_first_output_to_discord.py

      - name: Set up GitHub token for pushing
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          DATE=$(date '+%Y-%m-%d')
          git add results/ || true
          git commit -m "Ran event for $DATE" || echo "No changes to commit"
          git push || echo "No changes to push"
